#!/usr/bin/env python3
"""
teacher_trial.py
----------------
Phase B: fair A/B of answer-generation teachers (Opus vs Gemini) on ONE fixed
set of 50 contexts, scoring brevity + groundedness on the same briefing prompt.

Outputs (in ./trial/):
  contexts_50.jsonl       the 50 shared contexts (teacher-independent, one teacher generates them)
  arms/<arm>/<id>.json    every answer, keyed by context id
  trial-results.json      per-arm stats: median words, entity coverage, fabrication count, abstain correctness, hedge rate
  blind-review.csv        10 random rows anonymized (arm label removed) with both answers side by side
                          -> Daniel reviews 1-5, we unblind afterwards.

Key check first: prints which of ANTHROPIC_API_KEY / GEMINI_API_KEY are present
and aborts cleanly naming what's missing. No key values are ever printed.

Usage:
    pip install anthropic google-genai
    export ANTHROPIC_API_KEY=...   # known to exist
    export GEMINI_API_KEY=...      # if available (Google AI API key from ai.google.dev)
    python teacher_trial.py --out-dir trial
    python teacher_trial.py --arms opus --out-dir trial   # opus-only fallback
"""

import argparse
import json
import os
import random
import re
import statistics
from pathlib import Path

# --- fixed context set: generated by a single teacher (default Opus), reused
#     verbatim by every arm. This is what makes the comparison fair.
CONTEXT_GENERATOR = "opus"          # only opus is trusted for context gen here
DEFAULT_OPUS_MODEL = "claude-opus-4-8"
DEFAULT_GEMINI_MODEL = "gemini-2.5-pro"          # tune after OQ1 (Google One quota)

DOMAINS = [
    ("health", "a person's medical appointments, treatment, and recovery in 2026"),
    ("career", "software engineering work: projects, workflows, on-call, tooling"),
    ("music", "playing in a band: rehearsals, gear, gigs, songwriting"),
    ("gaming", "retro game collecting and home-server builds"),
    ("baking", "sourdough hobby: starter, schedules, oven, family"),
    ("travel", "upcoming trips: flights, hotels, dates, budget"),
    ("family", "parenting a 14 year old: school, hockey, phone rules"),
    ("finance", "household budget, mortgage refi, investment index funds"),
    ("diy", "woodworking and CNC projects: machines, safety, shop"),
    ("fitness", "cycling training: zones, intervals, bike setup"),
    ("reading", "bookshelf: current reads, shelf of unread, recommendations"),
    ("home-lab", "self-hosting: Proxmox, Ceph, Docker, monitoring"),
]
CATEGORIES = {
    "factual": "A direct factual question with one exact answer (date, number, name) present in the findings.",
    "preference": "A question about stated preferences or standing instructions.",
    "enumeration": "A 'list all X / how many Y' question requiring several distinct items.",
    "contradiction": "Two findings give CONFLICTING values for the same fact. The answer must name both and refuse to pick one silently.",
    "supersession": "An old value AND a newer updated value exist. The answer must give the NEWER one only, as current.",
    "abstention": "The question has NO answer in the findings. The correct answer is a clean 'no information in memory'. Include plausible WRONG facts as distractors.",
    "summary": "A summary-of-patterns question over several findings across different dates.",
}
MIX = [  # per-50-batch category weights, sum=1
    ("factual", 20), ("preference", 15), ("enumeration", 20),
    ("contradiction", 10), ("supersession", 10), ("abstention", 10), ("summary", 15),
]

BRIEFING = """\
You are writing the IDEAL answer to a memory-recall query.

The context below is a pool of FINDINGS (derived facts and raw messages) from a \
memory system, plus a QUESTION from the user. Write the answer the best possible \
recall agent would give.

Hard rules:
1. ANSWER LENGTH: 1-3 short sentences, at most 50 words. No preamble, no "based on \
what I found", no re-stating the question, no bullet lists unless there is more \
than 2 items.
2. GROUNDED ONLY: every name, date, number, or item in your answer must come from \
the findings. Do NOT add knowledge, do NOT guess, do NOT soften with "likely" or \
"probably".
3. CONTRADICTION category: name BOTH conflicting values and state the conflict \
explicitly.
4. SUPERSESSION category: give only the most recent value.
5. ABSTENTION category: say plainly that no information about this is stored; \
mention none of the distractor facts.
6. QUOTE exact values (dates/numbers/names) - do not paraphrase them.

Return ONLY a JSON object, no prose, no code fences:
{{"answer": "..."}}
"""

HEDGE = re.compile(r"\b(likely|probably|might|maybe|perhaps|possibly|seems?|appears?|perhaps|presumably)\b", re.I)


def generate_one(arm: str, system: str, user: str) -> str:
    if arm == "opus":
        from anthropic import Anthropic
        r = Anthropic().messages.create(
            model=DEFAULT_OPUS_MODEL, system=system,
            messages=[{"role": "user", "content": user}], max_tokens=1024,
        )
        return r.content[0].text
    if arm == "gemini":
        from google import genai
        r = genai.Client().models.generate_content(
            model=DEFAULT_GEMINI_MODEL,
            contents=[{"role": "user", "parts": [{"text": system + "\n\n" + user}]}],
        )
        return r.text
    raise ValueError(arm)


def extract_json(text: str):
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.MULTILINE).strip()
    s, e = text.find("{"), text.rfind("}")
    if s == -1 or e == -1:
        raise ValueError("no JSON object in: " + text[:200])
    return json.loads(text[s:e+1])


def build_contexts(n: int, out: Path) -> list[dict]:
    """Generate n contexts with the trusted context generator (op)."""
    random.seed()
    domains = [d for d, _ in DOMAINS]
    cats = []
    for name, w in MIX:
        cats += [name] * w
    contexts = []
    for i in range(n):
        domain = domains[i % len(domains)]
        cat = cats[i % len(cats)]
        user = (
            f"Write ONE synthetic memory-recall context. Domain: {domain}. Category: {cat}\n"
            f"(category definition: {CATEGORIES[cat]})\n"
            "Return ONLY a JSON object, no prose, no code fences:\n"
            "{\n"
            f'  "id": "{i:04d}",\n'
            f'  "persona": "<2-line bio of the person whose memory this is>",\n'
            '  "question": "<the user question, 5-25 words>",\n'
            '  "findings": [{"text": "<a fact or short message, 10-60 words>", "date": "2026-0X-XX"}, ... 6-10 findings ...],\n'
            '  "distractors": ["<plausible WRONG fact in the same domain>", ... 3-5 ...],\n'
            '  "required_facts": ["<entity/value every correct answer must contain>", ...],\n'
            '  "forbidden_facts": ["<distractor values a correct answer must NOT assert>", ...]\n'
            "}\n"
            "Rules: findings must be internally consistent with the category; for \
            'contradiction' exactly two findings must conflict; for 'supersession' one \
            finding must say it was changed and the other hold the new value; for \
            'abstention' the question must target a topic ABSENT from findings while \
            distractors are plausible near-misses."
        )
        ctx = extract_json(generate_one(CONTEXT_GENERATOR, "You are building training contexts for an LLM fine-tuning dataset.", user))
        assert ctx.get("persona") and ctx.get("question") and ctx.get("findings"), f"malformed context {i}"
        contexts.append(ctx)
        print(f"[ctx {len(contexts):3d}/{n}] {ctx['id']} {ctx['question'][:60]}")
    out.write_text("\n".join(json.dumps(c) for c in contexts) + "\n")
    return contexts


def score_arm(ctxs: list[dict], answers: dict, arm: str) -> dict:
    words, coverage, fab, abstain_ok, hedge = [], [], 0, 0, 0
    for c in ctxs:
        a = (answers.get(c["id"], {}) or {}).get("answer", "")
        ws = len(a.split())
        words.append(ws)
        req = c.get("required_facts") or []
        if c.get("category") == "abstention":
            if (ws <= 40 and not HEDGE.search(a)):
                abstain_ok += 1
            coverage.append(1.0)  # abstain: no required facts by design
        else:
            hits = sum(1 for r in req if r.lower() in a.lower() or any(w in a.lower() for w in r.lower().split()) if not any(f in a.lower() for f in (c.get("forbidden_facts") or [])))
            # simpler, stricter: entity present AND no forbidden asserted
            ok = 0
            for r in req:
                if r.lower() in a.lower():
                    ok += 1
                else:
                    toks = r.lower().split()
                    if toks and all(t in a.lower() for t in toks[:2]):
                        ok += 1
            coverage.append(ok / max(1, len(req)))
        fbs = c.get("forbidden_facts") or []
        if c.get("category") != "abstention" and fbs and any(f.lower() in a.lower() for f in fbs):
            fab += 1
        if HEDGE.search(a):
            hedge += 1
    n = max(1, len(ctxs))
    return {
        "arm": arm,
        "n": len(ctxs),
        "median_words": int(statistics.median(words)) if words else None,
        "max_words": max(words) if words else None,
        "entity_coverage": round(statistics.mean(coverage), 3) if coverage else None,
        "fabrication_rows": fab,
        "abstention_correct": abstain_ok,
        "hedge_rows": hedge,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arms", default="opus,gemini", help="comma list of arms to run")
    ap.add_argument("--n", type=int, default=50)
    ap.add_argument("--out-dir", default="trial")
    args = ap.parse_args()

    arms = [a.strip() for a in args.arms.split(",") if a.strip()]
    have = {a: bool(os.environ.get({"opus": "ANTHROPIC_API_KEY", "gemini": "GEMINI_API_KEY"}[a])) for a in arms}
    missing = [a for a in arms if not have[a]]
    for a in arms:
        print(f"arm {a:8s} key {'OK' if have[a] else 'MISSING'}")
    if missing:
        print("Missing keys for:", ", ".join(missing), "-> set ANTHROPIC_API_KEY and/or GEMINI_API_KEY and re-run (or --arms opus).")
        return 1

    root = Path(args.out_dir)
    (root / "arms").mkdir(parents=True, exist_ok=True)

    ctx_file = root / "contexts_50.jsonl"
    if ctx_file.exists():
        ctxs = [json.loads(l) for l in ctx_file.read_text().splitlines() if l.strip()]
        print(f"loaded {len(ctxs)} existing contexts")
    else:
        ctxs = build_contexts(args.n, ctx_file)

    results = []
    review_rows = []
    for arm in arms:
        print(f"\n=== arm: {arm}")
        answers = {}
        arm_dir = root / "arms" / arm
        arm_dir.mkdir(parents=True, exist_ok=True)
        for c in ctxs:
            user = BRIEFING + "\n\nPERSONA: " + c["persona"] + "\n\nFINDINGS:\n" + "\n".join(f"- [{f['date']}] {f['text']}" for f in c["findings"]) + "\n\nDistractors (WRONG - must not be asserted):\n" + "\n".join("- " + d for d in c["distractors"]) + "\n\nQUESTION: " + c["question"]
            try:
                raw = generate_one(arm, "You write terse, fully grounded answers for a memory-recall fine-tuning dataset.", user)
                ans = extract_json(raw).get("answer", raw)
            except Exception as e:
                ans = f"__FAILED__: {type(e).__name__}: {e}"
            rec = {"id": c["id"], "answer": ans, "category": c.get("category")}
            (arm_dir / f"{c['id']}.json").write_text(json.dumps(rec, indent=1))
            answers[c["id"]] = rec
            print(f"[{arm} {c['id']}] {len(ans.split())}w  {ans[:70]}")
        results.append(score_arm(ctxs, answers, arm))

    (root / "trial-results.json").write_text(json.dumps(results, indent=1))
    print("\n---- SCORES ----")
    for r in results:
        print(json.dumps(r))

    # blind review CSV: 10 rows, arms anonymized A/B
    import csv
    rng = random.Random(523)
    pick = rng.sample(ctxs, min(10, len(ctxs)))

    def arm_answer(arm, cid):
        return (root / f"arms/{arm}/{cid}.json").read_text()

    with open(root / "blind-review.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["id", "category", "question", "answer_A", "answer_B"])
        for c in pick:
            a = json.loads(arm_answer(arms[0], c["id"])).get("answer", "")
            b = json.loads(arm_answer(arms[1], c["id"])).get("answer", "") if len(arms) > 1 else ""
            w.writerow([c["id"], c.get("category", ""), c["question"], a, b])
    blinding = ", ".join(f"{a}={chr(65+i)}" for i, a in enumerate(arms))
    print(f"\nblind-review.csv written ({len(pick)} rows) - review 1-5 blind, tell us your picks; we unblind via: {blinding}")


if __name__ == "__main__":
    raise SystemExit(main())
